language: java
jdk: openjdk12

services:
  - docker

script:
  - ./gradlew clean application:build

after_script:
  - docker build . -t inventory-service
#  - docker run -d -p 8081:8080 -t inventory-service
